apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: node-4424
  janus-idp.io/tekton: node-4424
  backstage.io/kubernetes-id: node-4424
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: node-4424
resources: 
- deployment.yaml
- route.yaml
- service.yaml
